### ISSUE TITLE
I can't get my Lone Ranger soundtrack. OH NO!

### ISSUE THREAD

**Issue by plgagne** [obskyr/khinsider#19]
Traceback (most recent call last):
  File "/Users/plgagne/Music/khinsider-master/khinsider.py", line 488, in <module>
    doIt()
  File "/Users/plgagne/Music/khinsider-master/khinsider.py", line 464, in doIt
    download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "/Users/plgagne/Music/khinsider-master/khinsider.py", line 356, in download
    Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "/Users/plgagne/Music/khinsider-master/khinsider.py", line 285, in download
    for song in self.songs:
  File "/Users/plgagne/Music/khinsider-master/khinsider.py", line 130, in lazy_version
    setattr(self, attr_name, func(self))
  File "/Users/plgagne/Music/khinsider-master/khinsider.py", line 249, in songs
    urls = [a['href'] for a in anchors]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by obskyr** [comment]
Thanks for the report! It's all fixed up now. Download the latest version and it should work just fine.

**Comment by plgagne** [comment]
I can download my Lone Ranger soundtrack!
