### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by TheSacredPixel** [obskyr/khinsider#20]
Getting the following when trying to download [under-night-in-birth](https://downloads.khinsider.com/game-soundtracks/album/under-night-in-birth). Happens right before track 13, which contains the ♪ character (U+266A).

```
Traceback (most recent call last):
  File "G:\Downloads\khinsider-master\khinsider.py", line 481, in <module>
    doIt()
  File "G:\Downloads\khinsider-master\khinsider.py", line 457, in doIt
    download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "G:\Downloads\khinsider-master\khinsider.py", line 349, in download
    Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "G:\Downloads\khinsider-master\khinsider.py", line 287, in download
    friendlyDownloadFile(file, path, file.filename, fileNumber, totalFiles, verbose)
  File "G:\Downloads\khinsider-master\khinsider.py", line 168, in friendlyDownloadFile
    print("Downloading {}: {}...".format(numberStr, name))
  File "C:\Users\User\.windows-build-tools\python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u266a' in position 51: character maps to <undefined>
```

**Comment by obskyr** [comment]
Thanks for the report! Apparently I'd broken unicode support again while doing the recent rewrite. It's all fixed now!

**Comment by TheSacredPixel** [comment]
Works! Thanks a lot!
