### ISSUE TITLE
Issue with reading certain characters? (Download messed up when encountering track with question mark)

### ISSUE THREAD

**Issue by nisbahmumtaz** [obskyr/khinsider#24]
Here's the album in question:
https://downloads.khinsider.com/game-soundtracks/album/osu-tatakae-ouendan-2

When it got to track 8, it gave me this error, and abruptly stopped the download.
Here's the whole log, from start to fin:

```
Getting song list...
Skipping over 01/20: 01.AI - Believe.mp3. Already exists.
Skipping over 02/20: 02.ZZ - Samurai Blue.mp3. Already exists.
Skipping over 03/20: 03.Hirai Ken - POP.STAR.mp3. Already exists.
Skipping over 04/20: 04.Hitomi Yaida - Go my way.mp3. Already exists.
Skipping over 05/20: 05.FLOW - Okuru Kotoba.mp3. Already exists.
Skipping over 06/20: 06.HOTEI TOMOYAS - Bambina.mp3. Already exists.
Skipping over 07/20: 07.HYDE - COUNTDOWN.mp3. Already exists.
Downloading 08/20: 08.mihimaru GT -  Kibun Joujou??.mp3...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "C:\Users\john\Desktop\utilities\khinsider-master\khinsider.py", line 473, in <module>
    doIt()
  File "C:\Users\john\Desktop\utilities\khinsider-master\khinsider.py", line 449, in doIt
    download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\john\Desktop\utilities\khinsider-master\khinsider.py", line 341, in download
    Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\john\Desktop\utilities\khinsider-master\khinsider.py", line 282, in download
    friendlyDownloadFile(file, path, file.filename, fileNumber, totalFiles, verbose)
  File "C:\Users\john\Desktop\utilities\khinsider-master\khinsider.py", line 168, in friendlyDownloadFile
    file.download(path)
  File "C:\Users\john\Desktop\utilities\khinsider-master\khinsider.py", line 333, in download
    with open(path, 'wb') as outFile:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\john\\Desktop\\utilities\\khinsider-master\\osu-tatakae-ouendan-2\\08.mihimaru GT -  Kibun Joujou??.mp3'
```

**Comment by obskyr** [comment]
Ah, I see what's happening here. Linux allows `?` in filenames, while Windows doesn't. Thanks for the report - I'll fix it in a bit!

**Comment by nisbahmumtaz** [comment]
Damn, what a fast response.
Appreciate for your work on the script, btw.

**Comment by obskyr** [comment]
Fixed it! Lemme know if there's anything else. Thanks for using khinsider.py! 😄
