### ISSUE TITLE
Can't download if name contains unicode

### ISSUE THREAD

**Issue by fzyukio** [obskyr/khinsider#27]
Was downloading: https://downloads.khinsider.com/game-soundtracks/album/the-world-ends-with-you-twewy-soundtrack-full-collection

Failed at track 1-36: "De╠üja╠Ć Vu"

Traceback
```
Traceback (most recent call last):
  File "khinsider.py", line 503, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 469, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 361, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 299, in download
    if not friendlyDownloadFile(file, path, fileNumber, totalFiles, verbose):
  File "khinsider.py", line 172, in friendlyDownloadFile
    if not os.path.exists(path):
  File "/home/fzy/workspace/pyplayground/.venv/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 97-98: ordinal not in range(128)
```

**Comment by obskyr** [comment]
I thought the days of character encoding errors were long behind me... It seems that I must return to set old mistakes right once again.

What I mean to say is, it looks like your filesystem encoding might be ASCII. What OS (and OS version) are you on?

**Comment by fzyukio** [comment]
Yep, it's the encoding problem
Setting `export LANG='en_US.UTF-8'; export LC_ALL='en_US.UTF-8'` fixed it.

Ubuntu 16.04

**Comment by obskyr** [comment]
Ah, I see. Thanks for the info - that saves me a whole lot of searchin' around. I'll put in some sort of error handling for non-Unicode filesystems.

**Comment by obskyr** [comment]
Fixed with a notice to the user!

```
$ LANG="en_US.ascii" LC_ALL="en_US.ascii" python3 ./khinsider.py the-world-ends-with-you-twewy-soundtrack-full-collection
Getting song list...
Downloading 01/90: 1-01 It's So Wonderful.mp3...
...
Downloading 35/90: 1-35 Lullaby For You.mp3...
Downloading 36/90: 1-36 De??ja?? Vu.mp3 (replaced characters outside the filesystem's "ascii" encoding)...
Downloading 37/90: 1-37 Transformation.mp3...
...
```
