### ISSUE TITLE
problem in downloadingsoundtrack

### ISSUE THREAD

**Issue by a-j-smith** [obskyr/khinsider#30]
`An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "khinsider.py", line 556, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 506, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 391, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 315, in download
    if not friendlyDownloadFile(file, path, fileNumber, totalFiles, verbose):
  File "khinsider.py", line 189, in friendlyDownloadFile
    file.download(path)
  File "khinsider.py", line 383, in download
    with open(path, 'wb') as outFile:
FileNotFoundError: [Errno 2] No such file or directory: "/home/adam/Music/Zelda/Majora's-Mask/141 Marshland.mp3"
`

**Comment by a-j-smith** [comment]
It worked when I tried again
