### ISSUE TITLE
bs4 not work, why?

### ISSUE THREAD

**Issue by tuxiston** [obskyr/khinsider#32]
python khinsider.py jumping-flash
/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "khinsider.py", line 556, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 506, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 391, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 295, in download
    path = os.path.join(os.getcwd(), path)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

**Comment by obskyr** [comment]
Hmm. How did you install Beautiful Soup? And what OS are you on? If `soupsieve` isn't installed, that's mighty strange – it's typically installed as a dependency when you install Beautiful Soup 4.
