### ISSUE TITLE
Can not download japanese language music file

### ISSUE THREAD

**Issue by pachimonopower** [obskyr/khinsider#35]
Report the following error.

```
python khinsider.py blue-reflection-ost

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "khinsider.py", line 588, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 532, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 407, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 311, in download
    path = os.path.join(os.getcwd(), path)
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 35: ordinal not in range(128)
```

**Comment by pachimonopower** [comment]
de648c2 on 15 Jun

```
[Success code]
308 : #path = os.path.join(os.getcwd(), path)
309 : os.path.join(os.getcwd().decode('cp932').encode('utf-8'), path.encode('utf-8'))
```

this is japanese environment problem.
if multi byte char include in current directory, need to currect encoding.

**Comment by obskyr** [comment]
Try this latest commit, please! `khinsider.py` should be compatible with all locales out of the box, and I think c215747 might fix your problem.

**Comment by pachimonopower** [comment]
So cool!
It worked without problems:thumbsup:

**Comment by obskyr** [comment]
Great to hear! ご協力ありがとうございました！
