### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by NezyPC** [obskyr/khinsider#36]
Has been working great for a long time, suddenly getting this error:

C:\Users\Gary>khinsider.py blood-2-the-chosen-soundtrack-pc "E:\Downloads\khinsider.py\Blood 2 - The Chosen Soundtrack (PC)"
C:\Users\Gary\AppData\Local\Programs\Python\Python37\Scripts\khinsider.py:39: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp # To check modules without importing them.
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python37\Scripts\khinsider.py", line 556, in <module>
    sys.exit(doIt())
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python37\Scripts\khinsider.py", line 506, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python37\Scripts\khinsider.py", line 391, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python37\Scripts\khinsider.py", line 306, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python37\Scripts\khinsider.py", line 154, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**Comment by kioshimushi** [comment]
Yep happen today for me to, with a pretty similar traceback:

Traceback (most recent call last):
  File "C:\Users\Wayne_\khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "C:\Users\Wayne_\khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\Wayne_\khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\Wayne_\khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "C:\Users\Wayne_\khinsider.py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**Comment by clochefolle** [comment]
Hello all,
I stumbled upon the same exact error as yours, kioshimushi:

Traceback (most recent call last):
  File "khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "khinsider.py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**Comment by alexcu** [comment]
@NezyPC @kioshimushi @clochefolle As a temporary fix, replace **line 364** in the python script from:

```python
anchors = [p.find('a') for p in self._soup('p', string=re.compile(r'^\s*Click here to download'))]
```

to:

```python
anchors = [p for p in self._soup('a', href=re.compile("^http://23.237.126.42/ost"))]
```

This is just a _temporary_ fix, however, as the hosting server IP may change with time!

**Comment by NezyPC** [comment]
@alexcu Works like a charm so far! (It was line 347 for me, maybe I have an old version?) I can also see where I can look at the file info on the site and grab the server name in case it ever changes. I will certainly send an update if I run into any problems with the fix.

I love this tool so much! Thank you!

**Comment by obskyr** [comment]
Thanks for the reports, everyone! As of 00453f1, this issue is fixed – download the latest version and it should run fine. It made me really happy to see all these reports so quickly! Since `khinsider.py` is an entirely local program, I have no insight into whether people are using it at all, so it was really nice to see that it apparently *is* being used!

Enjoy! :star:
