### ISSUE TITLE
When downloading castlevania-symphony-of-the-night

### ISSUE THREAD

**Issue by billautd** [obskyr/khinsider#38]
Traceback (most recent call last):
  File "C:\Users\David\Documents\KHInsider Downloader\khinsider.py", line 566, in <module>
    sys.exit(doIt())
  File "C:\Users\David\Documents\KHInsider Downloader\khinsider.py", line 516, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\David\Documents\KHInsider Downloader\khinsider.py", line 401, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\David\Documents\KHInsider Downloader\khinsider.py", line 316, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "C:\Users\David\Documents\KHInsider Downloader\khinsider.py", line 164, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**Comment by obskyr** [comment]
This is probably the same problem as in #36, and should be fixed in the latest version – try again after downloading the latest version, and let me know how it goes!

**Comment by billautd** [comment]
Downloaded the latest version and it's all better, thanks !
