### ISSUE TITLE
Failing to download album

### ISSUE THREAD

**Issue by UnixNight** [obskyr/khinsider#47]
Im getting this when I try to download this album.

https://downloads.khinsider.com/game-soundtracks/album/sonic-the-hedgehog-boom-the-music-from-sonic-cd-and-sonic-

```
PS F:\Downloads\khinsider-master> .\khinsider.py --format flac sonic-the-hedgehog-boom-the-music-from-sonic-cd-and-sonic-                                       Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "F:\Downloads\khinsider-master\khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "F:\Downloads\khinsider-master\khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "F:\Downloads\khinsider-master\khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "F:\Downloads\khinsider-master\khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "F:\Downloads\khinsider-master\khinsider.py", line 175, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range
PS F:\Downloads\khinsider-master>        
```                                                                                                                                                                                             

Happens with this as well.

https://downloads.khinsider.com/game-soundtracks/album/sonic-the-hedgehog-caf-selection

```PS F:\Downloads\khinsider-master> .\khinsider.py sonic-the-hedgehog-caf-selection                                                                               Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "F:\Downloads\khinsider-master\khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "F:\Downloads\khinsider-master\khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "F:\Downloads\khinsider-master\khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "F:\Downloads\khinsider-master\khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "F:\Downloads\khinsider-master\khinsider.py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range
PS F:\Downloads\khinsider-master>                                                                                                                                                                          ```

**Comment by obskyr** [comment]
Hmm – it doesn't occur for me with the same command.
* Are you using the latest version of the script?
* Was it a temporary fault with the KHInsider website? Does it work if you try it now?
If not, what version of Python and what OS are you on?

**Comment by UnixNight** [comment]
My apologies, I didn't realize there was a new version of the script. Closing this issue

**Comment by obskyr** [comment]
Nice; glad you got it solved.
