### ISSUE TITLE
Some albums cannot be downloaded

### ISSUE THREAD

**Issue by Pretzelek** [obskyr/khinsider#59]
Hello.
Some albums fail to download.
These are:
-t-w-y-a-o-gyakuten-meets-jazz-soul
robot-wants-puppy-gamerip
shattered-horizon-2009-gamerip

Here's output when attempting to download them:

```
Microsoft Windows [Version 10.0.17763.2029]
(c) 2018 Microsoft Corporation. All rights reserved.

F:\Temporary>khinsider.py -t-w-y-a-o-gyakuten-meets-jazz-soul
No soundtrack specified! As the first parameter, use the name the soundtrack uses in its URL.
If you want to, you can also specify an output directory as the second parameter.
You can also search for soundtracks by using your search term as parameter - as long as it's not an existing soundtrack.

For detailed help and more options, run "khinsider.py --help".

F:\Temporary>khinsider.py robot-wants-puppy-gamerip
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "F:\Temporary\khinsider.py", line 599, in <module>
    sys.exit(doIt())
  File "F:\Temporary\khinsider.py", line 543, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "F:\Temporary\khinsider.py", line 413, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "F:\Temporary\khinsider.py", line 326, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "F:\Temporary\khinsider.py", line 171, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

F:\Temporary>khinsider.py shattered-horizon-2009-gamerip
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "F:\Temporary\khinsider.py", line 599, in <module>
    sys.exit(doIt())
  File "F:\Temporary\khinsider.py", line 543, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "F:\Temporary\khinsider.py", line 413, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "F:\Temporary\khinsider.py", line 326, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "F:\Temporary\khinsider.py", line 171, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

```

**Comment by evanclue** [comment]
i have a similar issue.

`khinsider.py beatmania
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "D:\Downloads\khinsider-master\khinsider.py", line 591, in <module>
    sys.exit(doIt())
  File "D:\Downloads\khinsider-master\khinsider.py", line 535, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "D:\Downloads\khinsider-master\khinsider.py", line 410, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "D:\Downloads\khinsider-master\khinsider.py", line 322, in download
    for song in self.songs:
  File "D:\Downloads\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "D:\Downloads\khinsider-master\khinsider.py", line 286, in songs
    anchors = [tr.find('a') for tr in table('tr') if not tr.find('th')]
TypeError: 'NoneType' object is not callable`

**Comment by EverThingy** [comment]
Same here for silver-surfer-ost-1990-nes. 
`python khinsider.py silver-surfer-ost-1990-nes
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "E:\Music\khinsider-master\khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "E:\Music\khinsider-master\khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "E:\Music\khinsider-master\khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "E:\Music\khinsider-master\khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "E:\Music\khinsider-master\khinsider.py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range`

**Comment by obskyr** [comment]
Thank you ever so kindly for the report! I've now fixed `robot-wants-puppy-gamerip` (a song title containing the string `&#` resulted in broken HTML) and `shattered-horizon-2009-gamerip` (one of the songs didn't exist, and instead just led to a 404 page).

As for `-t-w-y-a-o-gyakuten-meets-jazz-soul`, you can run `khinsider.py -- -t-w-y-a-o-gyakuten-meets-jazz-soul` – the `--` means “treat the following arguments as positional arguments”, which is needed when the soundtrack name starts with `-`. If you think it's a big enough issue that some special syntax should be added for it, or I should rejigger the whole argument parsing to treat unknown dash arguments as positionals, let me know – for now, though, this'll work.
