### ISSUE TITLE
Error when downloading Deltarune/Undertale OST

### ISSUE THREAD

**Issue by travistouchup** [obskyr/khinsider#64]
An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "C:\Users\ren\Desktop\khinsider-master\khinsider.py", line 599, in <module>
    sys.exit(doIt())
  File "C:\Users\ren\Desktop\khinsider-master\khinsider.py", line 543, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\ren\Desktop\khinsider-master\khinsider.py", line 413, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\ren\Desktop\khinsider-master\khinsider.py", line 325, in download
    for song in self.songs:
  File "C:\Users\ren\Desktop\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\ren\Desktop\khinsider-master\khinsider.py", line 289, in songs
    anchors = [tr.find('a') for tr in table('tr') if not tr.find('th')]
TypeError: 'NoneType' object is not callable

C:\Users\ren\Desktop\khinsider-master>

**Comment by ValsartaN7** [comment]
Hi, I get the same error.

I can't download any album or track. Everything got wrong just today. 
I'm using python 3.10.4-1. 

Here's the error I get : 
Traceback (most recent call last):
  File "/home/khinsider-master/khinsider.py", line 599, in <module>
    sys.exit(doIt())
  File "/home/khinsider-master/khinsider.py", line 543, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "/home/khinsider-master/khinsider.py", line 413, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "/home/khinsider-master/khinsider.py", line 319, in download
    if not set(self.availableFormats) & set(formatOrder):
  File "/home/khinsider-master/khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "/home/khinsider-master/khinsider.py", line 279, in availableFormats
    table = self._contentSoup.find('table', id='songlist')
  File "/home/khinsider-master/khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "/home/khinsider-master/khinsider.py", line 271, in _contentSoup
    if contentSoup.find('p').string == "No such album":
AttributeError: 'NoneType' object has no attribute 'find'}

Any idea about what's wrong ?

**Comment by ImMalding** [comment]
I also received a similar error which I first encountered today.

>Traceback (most recent call last):
  File "C:\Users\Nolan\khinsider.py", line 602, in <module>
    sys.exit(doIt())
  File "C:\Users\Nolan\khinsider.py", line 546, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\Nolan\khinsider.py", line 416, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\Nolan\khinsider.py", line 322, in download
    if not set(self.availableFormats) & set(formatOrder):
  File "C:\Users\Nolan\khinsider.py", line 152, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\Nolan\khinsider.py", line 282, in availableFormats
    table = self._contentSoup.find('table', id='songlist')
  File "C:\Users\Nolan\khinsider.py", line 152, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\Nolan\khinsider.py", line 274, in _contentSoup
    if contentSoup.find('p').string == "No such album":
AttributeError: 'NoneType' object has no attribute 'find'

I'm thinking something changed on the khinsider site itself, but I'm not sure.

**Comment by ViviRadio** [comment]
Getting the exact same error.

Does anyone know if this project still receives updates? I can't really see it anywhere.

**Comment by RGPZ** [comment]
The person who works on this is still active on Twitter, so I mentioned it to him.

**Comment by T-Craig** [comment]
Just chiming in to say that I'm getting the same error. I can only assume that something changed on the backend of KHInsider.

**Comment by kamilkrzyskow** [comment]
Possibly related to #65  
I've sent a somewhat 🤷‍♂️ working solution there.
