### ISSUE TITLE
Downloads not working.

### ISSUE THREAD

**Issue by Mrmegacham** [obskyr/khinsider#68]
Can't download new songs even though I had no issues earlier.

```
Traceback (most recent call last):
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 599, in <module>
    sys.exit(doIt())
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 543, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 413, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 325, in download
    for song in self.songs:
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 288, in songs
    table = self._contentSoup.find('table', id='songlist')
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\user\Downloads\khinsider-master\khinsider-master\khinsider.py", line 271, in _contentSoup
    if contentSoup.find('p').string == "No such album":
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by Mrmegacham** [comment]
I got it fixed by downloading the newer version mentioned by #66
