### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by Mann-Nova** [obskyr/khinsider#71]
Tried to download the Animal Crossing GC Rip page from khinsider, got this error:
 
khinsider.py animal-crossing-gc-rip
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 591, in <module>
    sys.exit(doIt())
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 535, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 410, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 322, in download
    for song in self.songs:
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 285, in songs
    table = self._contentSoup.find('table', id='songlist')
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\fl4m1\Music\~~~khinsider-master\khinsider-master\khinsider.py", line 268, in _contentSoup
    if contentSoup.find('p').string == "No such album":
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by Archetypic** [comment]
You have the most recent version of `khinsider.py`?

**Comment by Mann-Nova** [comment]
> 

Ah, didn't realize it was updated. Just downloaded the newest version and it's working now!

**Comment by pineapplemachine** [comment]
I ran into the same `'NoneType' object has no attribute 'find'` error, using a version of the script from about one year ago. I can confirm that pulling the newest version fixed the problem for me.
