### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by Vkoid** [obskyr/khinsider#72]
"Traceback (most recent call last):
  File "D:\vgm-music\khinsider-master\khinsider.py", line 681, in <module>
    sys.exit(doIt())
  File "D:\vgm-music\khinsider-master\khinsider.py", line 628, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "D:\vgm-music\khinsider-master\khinsider.py", line 457, in download
    return soundtrack.download(path, makeDirs, formatOrder, verbose)
  File "D:\vgm-music\khinsider-master\khinsider.py", line 367, in download
    os.makedirs(os.path.abspath(os.path.realpath(path)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\Brenn\\ D:'"

**Comment by Vkoid** [comment]
also thanks for making this, the other one i tried to use had a window that you couldnt move or close, just stuck there in the middle of the screen
