### ISSUE TITLE
Cant download from URL

### ISSUE THREAD

**Issue by soggaaa77** [obskyr/khinsider#76]
Hello,

I cant download from URL anymore. I did that long time ago, I dont know if my command is wrong or recent update disabled the downloading. Here is the output.

T:\khinsider-master>python khinsider.py https://downloads.khinsider.com/game-soundtracks/album/anno-1800-original-game-soundtrack-2019
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "T:\khinsider-master\khinsider.py", line 599, in <module>
    sys.exit(doIt())
  File "T:\khinsider-master\khinsider.py", line 543, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "T:\khinsider-master\khinsider.py", line 413, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "T:\khinsider-master\khinsider.py", line 325, in download
    for song in self.songs:
  File "T:\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "T:\khinsider-master\khinsider.py", line 288, in songs
    table = self._contentSoup.find('table', id='songlist')
  File "T:\khinsider-master\khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
  File "T:\khinsider-master\khinsider.py", line 271, in _contentSoup
    if contentSoup.find('p').string == "No such album":
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by soggaaa77** [comment]
Getting the last version fixed the issue. Sorry !
