### ISSUE TITLE
Can't add \ to download argument

### ISSUE THREAD

**Issue by gidgeesheep** [obskyr/khinsider#77]
I thought I could specify I only wanted disk 1 to download by adding a \1 or a \1* the to end of the title eg. "mario-kart-wii\1"

-----------------------------------ERROR---------------------------------
Traceback (most recent call last):
  File "C:\Users\Christian\Documents\.MUSIC DOWNLOADER\khinsider.py", line 681, in <module>
    sys.exit(doIt())
  File "C:\Users\Christian\Documents\.MUSIC DOWNLOADER\khinsider.py", line 628, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\Christian\Documents\.MUSIC DOWNLOADER\khinsider.py", line 457, in download
    return soundtrack.download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\Christian\Documents\.MUSIC DOWNLOADER\khinsider.py", line 358, in download
    for song in self.songs:
  File "C:\Users\Christian\Documents\.MUSIC DOWNLOADER\khinsider.py", line 160, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\Users\Christian\Documents\.MUSIC DOWNLOADER\khinsider.py", line 316, in songs
    anchors = [tr.find('a') for tr in table('tr') if not tr.find('th')]
TypeError: 'NoneType' object is not callable
----------------------------------------------------------------------------

**Comment by AzuzoraDev** [comment]
I had no issues with the most recent version on Windows PC. I suggest replacing old files with the new ones.
