### ISSUE TITLE
Error when running in Nitrous.IO

### ISSUE THREAD

**Issue by LucasOne** [obskyr/khinsider#8]
I get this error when running
myproject  python khinsider.py
Installing beautifulsoup4...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/beautifulsoup4-4.4.1.dist-info'
Storing debug log for failure in /home/nitrous/.pip/pip.log
Traceback (most recent call last):
  File "khinsider.py", line 60, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by Maverynthia** [comment]
I think I remember getting that error and I solved it by using Python 3.0 as I couldn't figure it out.

**Comment by obskyr** [comment]
I've never used Nitrous (never even heard of it until now, actually), so I don't really know what this is about. I'd assume maybe it doesn't like installing libraries through the actual program? One possibility is that it runs Python scripts with different permissions than what's required to access the `lib` directory. Maybe I should add an error message for that...

Try running these commands in whatever console Nitrous gives you (with `sudo` if it seems to require it):

```bash
pip install requests
pip install beautifulsoup4
```

Then see if it gets mad at you and report back.

**Comment by LucasOne** [comment]
khinsider git:(master) ✗ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install beautifulsoup4
  File "<stdin>", line 1
    pip install beautifulsoup4
              ^
SyntaxError: invalid syntax

**Comment by obskyr** [comment]
No, run it in the Linux console. If Nitrous gives you one of those. It boasts about "root access" on the site, so I'd assume it does.

**Comment by LucasOne** [comment]
ip install beautifulsoup4
Downloading/unpacking beautifulsoup4
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB): 81kB downloaded
Installing collected packages: beautifulsoup4
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/beautifulsoup4-4.4.1.dist-info'
Storing debug log for failure in /home/nitrous/.pip/pip.log

**Comment by LucasOne** [comment]
That's what I tried initially, still didn't work

**Comment by obskyr** [comment]
And Nitrous has pip, right? And you tried running with sudo?

**Comment by obskyr** [comment]
@LucasOne Here, [check this StackOverflow post](http://stackoverflow.com/a/17992898/2280091) out. Instead of `pip install`, try `pip install --user`.

**Comment by obskyr** [comment]
Psst, @LucasOne, how's it looking?

**Comment by LucasOne** [comment]
It looks there are restrictions after all on Nitrous.IO, so I ended up giving up. All the packages weren't working right, and some would not install due to folders actually being blocked/removed immediately from the filesystem. So I suppose it's best to close this issue.
