### ISSUE TITLE
Cannot use tool due to [AttributeError: 'NoneType' object has no attribute 'find']

### ISSUE THREAD

**Issue by xU77654x** [obskyr/khinsider#87]
I'm using Fedora 38 with Python 3.11.6 installed. I run the command `python khinsider.py xenoblade` in the master khinsider folder, and the song list fails.

```
[username@fedora khinsider-master]$ python khinsider.py xenoblade
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "/home/username/Documents/khinsider-master/khinsider.py", line 591, in <module>
    sys.exit(doIt())
             ^^^^^^
  File "/home/username/Documents/khinsider-master/khinsider.py", line 535, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/khinsider-master/khinsider.py", line 410, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/khinsider-master/khinsider.py", line 322, in download
    for song in self.songs:
                ^^^^^^^^^^
  File "/home/username/Documents/khinsider-master/khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
                            ^^^^^^^^^^
  File "/home/username/Documents/khinsider-master/khinsider.py", line 285, in songs
    table = self._contentSoup.find('table', id='songlist')
            ^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/khinsider-master/khinsider.py", line 149, in lazyVersion
    setattr(self, attrName, func(self))
                            ^^^^^^^^^^
  File "/home/username/Documents/khinsider-master/khinsider.py", line 268, in _contentSoup
    if contentSoup.find('p').string == "No such album":
       ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

I don't know if there's anything else that I should be doing here. This used to work for me in the past, but now it isn't working. Maybe the script needs to be re-written due to updates on the site itself?

**Comment by segacollection** [comment]
I have the same problem.
